### ISSUE TITLE
gulp-imagemin dependency vulnerabilities.

### ISSUE THREAD

**Issue by samcarecho** [virtua-tech/polymer-typescript-starter-kit#26]
tunnel-agent, a gulp-imagemin dependency, is being tagged by NPM audit as the source of many moderate severity vulnerabilities.

It seems that those vulnerabilities have not been dressed by either dropping the vulnerable package or by fixing the vulnerabilities. Therefore, I suggest that we drop gulp-imagemin until the issues are addressed properly. 

moderate      │ Memory Exposure
Package       │ tunnel-agent
Dependency of │ gulp-imagemin [dev]
Path          │ gulp-imagemin > imagemin-gifsicle > gifsicle > bin-build > download > caw > tunnel-agent
More info     │ https://nodesecurity.io/advisories/598

moderate      │ Memory Exposure
Package       │ tunnel-agent
Dependency of │ gulp-imagemin [dev]
Path          │ gulp-imagemin > imagemin-gifsicle > gifsicle > bin-wrapper > download > caw > tunnel-agent
More info     │ https://nodesecurity.io/advisories/598

moderate      │ Memory Exposure
Package       │ tunnel-agent
Dependency of │ gulp-imagemin [dev]
Path          │ gulp-imagemin > imagemin-jpegtran > jpegtran-bin > bin-build > download > caw > tunnel-agent 
More info     │ https://nodesecurity.io/advisories/598

moderate      │ Memory Exposure
Package       │ tunnel-agent
Dependency of │ gulp-imagemin [dev]
Path          │ gulp-imagemin > imagemin-jpegtran > jpegtran-bin > bin-wrapper > download > caw > tunnel-agent
More info     │ https://nodesecurity.io/advisories/598

moderate      │ Memory Exposure
Package       │ tunnel-agent
Dependency of │ gulp-imagemin [dev]
Path          │ gulp-imagemin > imagemin-optipng > optipng-bin > bin-build > download > caw > tunnel-agent
More info     │ https://nodesecurity.io/advisories/598

moderate      │ Memory Exposure
Package       │ tunnel-agent
Dependency of │ gulp-imagemin [dev]
Path          │ gulp-imagemin > imagemin-optipng > optipng-bin > bin-wrapper > download > caw > tunnel-agent
More info     │ https://nodesecurity.io/advisories/598

**Comment by kito99** [comment]
If we drop gulp altogether, we should be fine :-).

**Comment by samcarecho** [comment]
Solved on #27 push request, by removing gulp-imagemin.
